# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows:
  version: 2
  commit:
    jobs:
      - test-reports 
  nightly:
    triggers:
      - schedule:
          cron: "56 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - selenium 
     
