version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      - image: selenium/standalone-chrome:3.11.0
      
      # Specify service dependencies here if necessary  
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
            
    steps:
      - checkout    
      - setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
     
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
        
      - run:
          name: create docker network
          command: docker network create grid
